#!/usr/bin/env python3
"""Render canonical catalogs and facet views from data/papers.json."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Callable, Iterable


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "papers.json"
GENERATED_NOTICE = "<!-- Generated by scripts/render.py; edit data/papers.json instead. -->\n"

COLLECTION_LABELS = {
    "multi_teacher_on_policy": "Multi-Teacher On-Policy Distillation",
    "offline_multi_teacher": "Offline Multi-Teacher Distillation",
    "adjacent_alternative": "Adjacent and Alternative Paradigms",
    "single_teacher_foundation": "Single-Teacher Foundations",
    "review_tutorial": "Reviews and Tutorials",
}
COLLECTION_PATHS = {
    "multi_teacher_on_policy": Path("papers/multi-teacher-on-policy.md"),
    "offline_multi_teacher": Path("papers/offline-multi-teacher.md"),
    "adjacent_alternative": Path("papers/adjacent-alternatives.md"),
    "single_teacher_foundation": Path("papers/single-teacher-foundations.md"),
    "review_tutorial": Path("papers/reviews-tutorials.md"),
}
COLLECTION_INTROS = {
    "multi_teacher_on_policy": (
        "Works in this collection use states or trajectories generated by the current or "
        "near-current student and direct supervision from multiple independently identifiable "
        "teachers. Method papers, analyses, and system reports share one collection; record type "
        "is a separate facet."
    ),
    "offline_multi_teacher": (
        "Works in this collection distill multiple teachers or an ensemble using a static corpus, "
        "teacher-generated data, cached activations, or replay. They do not satisfy the repository's "
        "student-state criterion for strict MOPD."
    ),
    "adjacent_alternative": (
        "These works are useful boundary cases or alternatives: peer co-distillation, self/EMA "
        "distillation, privileged views, sibling rollouts, and offline replay. Their evidence notes "
        "state exactly which strict-MOPD condition does not hold."
    ),
    "single_teacher_foundation": (
        "These methods establish the generative or on-policy distillation machinery used by later "
        "MOPD work, but use one teacher rather than multiple independent supervisors."
    ),
    "review_tutorial": (
        "Surveys and tutorials that provide field-level context. Method-specific evidence fields are "
        "marked not applicable."
    ),
}

RECORD_LABELS = {
    "method": "Method",
    "analysis": "Analysis",
    "system_report": "System Report",
    "survey": "Survey",
    "tutorial": "Tutorial",
}
REGIME_LABELS = {
    "on_policy": "On Policy",
    "offline": "Offline",
    "hybrid": "Hybrid",
    "online_peer": "Online Peer",
    "self_distillation": "Self-Distillation",
    "not_applicable": "Not Applicable",
}
STATE_LABELS = {
    "current_student": "Current Student",
    "near_current_student": "Near-Current Student",
    "static_corpus": "Static Corpus",
    "teacher_generated": "Teacher-Generated",
    "replay_buffer": "Replay Buffer",
    "mixed": "Mixed",
    "not_applicable": "Not Applicable",
}
TOPOLOGY_LABELS = {
    "ensemble_to_one": "Ensemble to One",
    "independent_multi_teacher": "Independent Multi-Teacher",
    "specialist_pool": "Specialist Pool",
    "checkpoint_pool": "Checkpoint Pool",
    "heterogeneous_pool": "Heterogeneous Pool",
    "debate_collective": "Debate Collective",
    "peer_mutual": "Peer Mutual",
    "self_ema": "Self / EMA",
    "privileged_views": "Privileged Views",
    "sequential_chain": "Sequential Chain",
    "single_teacher": "Single Teacher",
}
MECHANISM_LABELS = {
    "direct_matching": "Direct Matching",
    "routing_selection": "Routing and Selection",
    "adaptive_weighting": "Adaptive Weighting",
    "conflict_resolution": "Conflict Resolution",
    "dynamic_scheduling": "Dynamic Scheduling",
    "heterogeneous_alignment": "Heterogeneous Alignment",
    "progressive_sequential": "Progressive and Sequential Transfer",
    "collective_deliberation": "Collective Deliberation",
    "not_applicable": "Not Applicable",
}
SIGNAL_LABELS = {
    "logits_distribution": "Logits / Distribution",
    "sampled_token_advantage": "Sampled-Token Advantage",
    "features": "Features",
    "relations": "Relations",
    "responses_rationales": "Responses / Rationales",
    "feedback_reward": "Feedback / Reward",
    "action_distribution": "Action Distribution",
    "latent_velocity": "Latent / Velocity",
    "gradients": "Gradients",
    "teacher_generated_data": "Teacher-Generated Data",
}
DOMAIN_LABELS = {
    "llm_general": "General LLMs",
    "llm_reasoning": "LLM Reasoning",
    "llm_agents": "LLM Agents",
    "llm_alignment": "LLM Alignment",
    "nlp": "NLP",
    "speech": "Speech",
    "vision": "Vision",
    "multimodal": "Multimodal",
    "generative_models": "Generative Models",
    "recommendation_search": "Recommendation and Search",
    "knowledge_graphs": "Knowledge Graphs",
    "robotics_embodied": "Robotics and Embodied AI",
    "scientific_healthcare": "Scientific and Healthcare",
    "general_machine_learning": "General Machine Learning",
}
ARTIFACT_LABELS = {"code": "Code", "project": "Project", "model": "Model", "data": "Data"}


def load_papers() -> tuple[dict[str, object], list[dict[str, object]]]:
    catalog = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    return catalog, catalog["papers"]


def anchor(paper_id: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", paper_id.casefold()).strip("-")


def sentence(text: str) -> str:
    text = " ".join(text.split())
    return text if text.endswith((".", "!", "?")) else text + "."


def labels(values: Iterable[str], mapping: dict[str, str]) -> str:
    rendered = [mapping[value] for value in values]
    return ", ".join(rendered) if rendered else "None"


def artifacts(paper: dict[str, object]) -> str:
    values = paper["artifacts"]
    if not values:
        return "None verified"
    return " · ".join(
        f"[{ARTIFACT_LABELS[item['type']]}]({item['url']})" for item in values
    )


def sort_recent(papers: Iterable[dict[str, object]]) -> list[dict[str, object]]:
    return sorted(papers, key=lambda paper: (paper["date"], paper["title"]), reverse=True)


def canonical_link(paper: dict[str, object]) -> str:
    path = COLLECTION_PATHS[paper["collection"]]
    return f"../{path.as_posix()}#{anchor(str(paper['id']))}"


def render_entry(paper: dict[str, object]) -> str:
    secondary = labels(paper["mechanism_tags"], MECHANISM_LABELS)
    return "\n".join(
        [
            f"<a id=\"{anchor(str(paper['id']))}\"></a>",
            f"- [{paper['title']}]({paper['paper']}) - {paper['date']}. {sentence(str(paper['summary']))}",
            (
                f"  - **Facets:** `{paper['id']}` · {RECORD_LABELS[paper['record_type']]} · "
                f"{REGIME_LABELS[paper['training_regime']]} · State: {STATE_LABELS[paper['state_source']]}"
            ),
            f"  - **Teacher topology:** {labels(paper['teacher_topology'], TOPOLOGY_LABELS)}",
            (
                f"  - **Mechanism:** {MECHANISM_LABELS[paper['primary_mechanism']]}"
                f" · Secondary: {secondary}"
            ),
            (
                f"  - **Signals and domains:** {labels(paper['signals'], SIGNAL_LABELS)}"
                f" · {labels(paper['domains'], DOMAIN_LABELS)}"
            ),
            f"  - **Classification evidence:** {sentence(str(paper['evidence']['classification_note']))}",
            f"  - **Artifacts:** {artifacts(paper)}",
        ]
    )


def group_config(collection: str) -> tuple[str, dict[str, str]]:
    if collection in {"multi_teacher_on_policy", "offline_multi_teacher"}:
        return "primary_mechanism", MECHANISM_LABELS
    if collection in {"adjacent_alternative", "single_teacher_foundation"}:
        return "training_regime", REGIME_LABELS
    return "record_type", RECORD_LABELS


def render_catalog(
    catalog: dict[str, object], papers: list[dict[str, object]], collection: str
) -> str:
    selected = [paper for paper in papers if paper["collection"] == collection]
    group_field, group_labels = group_config(collection)
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for paper in selected:
        grouped[str(paper[group_field])].append(paper)

    lines = [
        GENERATED_NOTICE.rstrip(),
        "",
        f"# {COLLECTION_LABELS[collection]}",
        "",
        COLLECTION_INTROS[collection],
        "",
        (
            f"**{len(selected)} records · metadata verified through "
            f"{catalog['last_verified']} · [Taxonomy](../resources/taxonomy.md)**"
        ),
    ]
    for group in sorted(grouped, key=lambda item: group_labels[item]):
        lines.extend(["", f"## {group_labels[group]}", ""])
        for paper in sort_recent(grouped[group]):
            lines.extend([render_entry(paper), ""])
    return "\n".join(lines).rstrip() + "\n"


def view_header(title: str, description: str, catalog: dict[str, object]) -> list[str]:
    return [
        GENERATED_NOTICE.rstrip(),
        "",
        f"# {title}",
        "",
        description,
        "",
        (
            "Entries link to their canonical catalog record. This is a derived view; edit "
            f"`data/papers.json` instead. Verified through {catalog['last_verified']}."
        ),
    ]


def view_item(paper: dict[str, object], detail: str) -> str:
    return f"- [{paper['title']}]({canonical_link(paper)}) - {detail}."


def render_system_reports(catalog: dict[str, object], papers: list[dict[str, object]]) -> str:
    selected = sort_recent(paper for paper in papers if paper["record_type"] == "system_report")
    lines = view_header(
        "System Reports",
        "Technical and model reports in which multi-teacher distillation is a material training stage, rather than a separate primary collection.",
        catalog,
    )
    lines.extend(["", f"## Reports ({len(selected)})", ""])
    for paper in selected:
        detail = (
            f"{paper['date']}; {MECHANISM_LABELS[paper['primary_mechanism']]}; "
            f"{labels(paper['domains'], DOMAIN_LABELS)}"
        )
        lines.append(view_item(paper, detail))
    return "\n".join(lines).rstrip() + "\n"


def render_grouped_view(
    catalog: dict[str, object],
    papers: list[dict[str, object]],
    *,
    title: str,
    description: str,
    mapping: dict[str, str],
    keys: Callable[[dict[str, object]], Iterable[str]],
    detail: Callable[[dict[str, object], str], str],
) -> str:
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for paper in papers:
        for key in keys(paper):
            grouped[key].append(paper)
    lines = view_header(title, description, catalog)
    for key in sorted(grouped, key=lambda item: mapping[item]):
        lines.extend(["", f"## {mapping[key]} ({len(grouped[key])})", ""])
        for paper in sort_recent(grouped[key]):
            lines.append(view_item(paper, detail(paper, key)))
    return "\n".join(lines).rstrip() + "\n"


def render_chronological(catalog: dict[str, object], papers: list[dict[str, object]]) -> str:
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for paper in papers:
        grouped[str(paper["date"])[:4]].append(paper)
    lines = view_header(
        "Chronological View",
        "The complete catalog ordered by first public date, with collection and record-type facets.",
        catalog,
    )
    for year in sorted(grouped, reverse=True):
        lines.extend(["", f"## {year} ({len(grouped[year])})", ""])
        for paper in sort_recent(grouped[year]):
            detail = (
                f"{paper['date']}; {COLLECTION_LABELS[paper['collection']]}; "
                f"{RECORD_LABELS[paper['record_type']]}"
            )
            lines.append(view_item(paper, detail))
    return "\n".join(lines).rstrip() + "\n"


def render_with_artifacts(catalog: dict[str, object], papers: list[dict[str, object]]) -> str:
    selected = sort_recent(paper for paper in papers if paper["artifacts"])
    lines = view_header(
        "Papers with Verified Artifacts",
        "Papers for which an author- or organization-linked code, project, model, or data artifact was verified.",
        catalog,
    )
    lines.extend(["", f"## Entries ({len(selected)})", ""])
    for paper in selected:
        kinds = ", ".join(ARTIFACT_LABELS[item["type"]] for item in paper["artifacts"])
        lines.append(view_item(paper, f"{kinds}; {COLLECTION_LABELS[paper['collection']]}"))
    return "\n".join(lines).rstrip() + "\n"


def build_outputs() -> dict[Path, str]:
    catalog, papers = load_papers()
    outputs: dict[Path, str] = {}
    for collection, path in COLLECTION_PATHS.items():
        outputs[path] = render_catalog(catalog, papers, collection)

    outputs[Path("views/system-reports.md")] = render_system_reports(catalog, papers)
    outputs[Path("views/by-domain.md")] = render_grouped_view(
        catalog,
        papers,
        title="By Domain",
        description="A cross-cutting view of application domains. Multi-domain papers can appear in more than one section.",
        mapping=DOMAIN_LABELS,
        keys=lambda paper: paper["domains"],
        detail=lambda paper, _key: (
            f"{COLLECTION_LABELS[paper['collection']]}; {MECHANISM_LABELS[paper['primary_mechanism']]}"
        ),
    )
    outputs[Path("views/by-mechanism.md")] = render_grouped_view(
        catalog,
        papers,
        title="By Mechanism",
        description="Primary and secondary combination mechanisms. A paper can appear in more than one section.",
        mapping=MECHANISM_LABELS,
        keys=lambda paper: [paper["primary_mechanism"], *paper["mechanism_tags"]],
        detail=lambda paper, key: (
            f"{'Primary' if paper['primary_mechanism'] == key else 'Secondary'} facet; "
            f"{COLLECTION_LABELS[paper['collection']]}"
        ),
    )
    outputs[Path("views/by-supervision-signal.md")] = render_grouped_view(
        catalog,
        papers,
        title="By Supervision Signal",
        description="The targets through which teacher knowledge reaches the student. Papers with several targets appear in each applicable section.",
        mapping=SIGNAL_LABELS,
        keys=lambda paper: paper["signals"],
        detail=lambda paper, _key: (
            f"{COLLECTION_LABELS[paper['collection']]}; {MECHANISM_LABELS[paper['primary_mechanism']]}"
        ),
    )
    outputs[Path("views/by-teacher-topology.md")] = render_grouped_view(
        catalog,
        papers,
        title="By Teacher Topology",
        description="How supervision sources relate to one another. Papers can carry multiple topology facets.",
        mapping=TOPOLOGY_LABELS,
        keys=lambda paper: paper["teacher_topology"],
        detail=lambda paper, _key: (
            f"{COLLECTION_LABELS[paper['collection']]}; {MECHANISM_LABELS[paper['primary_mechanism']]}"
        ),
    )
    outputs[Path("views/chronological.md")] = render_chronological(catalog, papers)
    outputs[Path("views/with-artifacts.md")] = render_with_artifacts(catalog, papers)
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale")
    args = parser.parse_args()
    outputs = build_outputs()

    stale: list[str] = []
    for relative, content in outputs.items():
        path = ROOT / relative
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(relative.as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    if stale:
        print("Generated catalogs are stale:", file=sys.stderr)
        for path in stale:
            print(f"- {path}", file=sys.stderr)
        print("Run: python3 scripts/render.py", file=sys.stderr)
        return 1
    if args.check:
        print(f"Generated catalogs are current ({len(outputs)} files).")
    else:
        print(f"Rendered {len(outputs)} files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
